swagger: "2.0"
info:
  description: "Aplicacion para meetups Santander"
  version: "1.0.0"
  title: "Meetups Santander"
host: "google.com"
basePath: "/api"
tags:
  - name: "Meet ups"
    description: "Everything about your Meet ups"
paths:
  /meet-ups:
    post:
      tags:
        - "Meet ups"
      summary: "Create a new Meetup"
      description: "Create a new Meetup"
      operationId: "addMeetup"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "MeetupRequest"
          description: "meetup request"
          required: true
          schema:
            $ref: "#/definitions/MeetupRequest"
      responses:
        "201":
          description: "successful response"
          schema:
            $ref: '#/definitions/Meetup'
definitions:
  Meetup:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Meetup Id"
        example: "1"
      attendees:
        type: "integer"
        description: "amount of people"
        example: "6"
      description:
        type: "string"
        description: "meetup description"
        example: "A new Meetup"
  MeetupRequest:
    type: "object"
    required:
      - description
    properties:
      description:
        type: "string"
        description: "meetup description"
        example: "A new Meetup"
